name = "Stargate: ReLeveled"
author = "RedΛngel"
version = "2.0.3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "705011000f39f85c097acaf8b511cd6d076cf7c735b5896f8b7927cdfa1241c8"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.252"

[options]
acceptable-game-versions = ["1.21.1"]
