name = "Stargate: ReLeveled"
author = "RedΛngel"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40c9954b5d07dacfa7935b95d9d6be74901949cf94beb54db36425d4e2b26a72"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.220"

[options]
acceptable-game-versions = ["1.21.1"]
