name = "Stargate: ReLeveled"
author = "RedΛngel"
version = "21.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae7fb511bc1a1f83942e079efafcd35f68142f548aba6e3eac20975ebe2ee8fc"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.248"

[options]
acceptable-game-versions = ["1.21.1"]
