
#General Config Section. See https://srpc.fdd-docs.com/introduction/
[general]
	#The Application ID of the Discord App to use
	applicationID = "762726289341677668"
	#Enable/Disable the mod
	enabled = true
	#Enable/Disable debugging mode. WARNING: MAY CAUSE LOG SPAM!
	debugging = false
	#Display the Icon and Pack Name in place of LargeImage from compatible launchers. DOES NOT WORK WITH CUSTOM APPS! ONLY THE DEFAULT ONE!
	launcherIntegration = false
	#Allow using local image files, as RPC icons
	rpcImageServer = false
	#The URL of the RPC image server that will be used for local images. Restart required when changed
	rpcImageServerUrl = "https://rpcavatar.firstdark.dev"
	#Internal Version Number. NO TOUCHY!
	version = 26

#The Game Loading event
[init]
	#Enable/Disable the Game Loading Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[init.presence]]
		type = "PLAYING"
		description = "Minecraft is loading"
		state = "Game Starting..."
		largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/logo.png"]
		largeImageText = "It's Minecraft {{game.version}}, but modded"
		smallImageKey = ["mclogo"]
		smallImageText = "{{game.mods}} mods installed"
		streamingActivityUrl = "https://twitch.tv/twitch"

#The Main Menu event
[main_menu]
	#Enable/Disable the Main Menu Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[main_menu.presence]]
		type = "PLAYING"
		description = "{{player.name}} is currently lazy"
		state = "Chilling in the menu"
		largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/logo.png"]
		largeImageText = "It's Minecraft {{game.version}}, but modded"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"

#The Server List event
[server_list]
	#Enable/Disable the Server List Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[server_list.presence]]
		type = "PLAYING"
		description = "{{player.name}} is looking for a server"
		state = "Searching for friends"
		largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/logo.png"]
		largeImageText = "It's Minecraft {{game.version}}, but modded"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"

#The Realms Screen event
[realms_list]
	#Enable/Disable the Realms Screen Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[realms_list.presence]]
		type = "PLAYING"
		description = "{{player.name}} is looking for a Realm"
		state = "Browsing Realms"
		largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/logo.png"]
		largeImageText = "It's Minecraft {{game.version}}, but modded"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"

#The Join Game Event
[join_game]
	#Enable/Disable the Join Game Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[join_game.presence]]
		type = "PLAYING"
		description = "{{player.name}} is joining a game"
		state = "Joining Game"
		largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/logo.png"]
		largeImageText = "It's Minecraft {{game.version}}, but modded"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"

#The Single Player Event
[single_player]
	#Enable/Disable the Single Player Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[single_player.presence]]
		type = "PLAYING"
		description = "Currently In {{world.name}}"
		state = "Playing lonely mode"
		largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/logo.png"]
		largeImageText = "It's Minecraft {{game.version}}, but modded"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"

#The Multi Player Event
[multi_player]
	#Enable/Disable the Multi Player Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[multi_player.presence]]
		type = "PLAYING"
		description = "Playing on {{server.name}} with {{server.players.count}} players"
		state = "Playing online"
		largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/logo.png"]
		largeImageText = "It's Minecraft {{game.version}}, but modded"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"

#The Realms Game Event
[realms]
	#Enable/Disable the Realms Game Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[realms.presence]]
		type = "PLAYING"
		description = "Playing on {{realm.name}}"
		state = "Playing on a Realm"
		largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/logo.png"]
		largeImageText = "It's Minecraft {{game.version}}, but modded"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"

#The Paused Event
[paused]
	#Enable/Disable the Pause Event
	enabled = true

	#List of RPCs that will be displayed at random
	[[paused.presence]]
		type = "PLAYING"
		description = "In the Pause Menu"
		state = "Game Paused"
		largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/logo.png"]
		largeImageText = "It's Minecraft {{game.version}}, but modded"
		smallImageKey = ["{{images.player}}"]
		smallImageText = "{{player.name}}"
		streamingActivityUrl = "https://twitch.tv/twitch"

#Fallback event for disabled events
[generic]

	#List of RPCs that will be displayed at random
	[[generic.presence]]
		type = "PLAYING"
		description = "Playing Minecraft"
		state = ""
		largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/logo.png"]
		largeImageText = "It's Minecraft {{game.version}}, but modded"
		smallImageKey = ["mclogo"]
		smallImageText = "{{game.mods}} mods installed"
		streamingActivityUrl = "https://twitch.tv/twitch"

#Custom Config Variables that you can use
[custom]
	#Must these variables be parsed along with other variables
	enabled = false
	#Your custom variables to add
	variables = []

#Dimension Information Overrides
[dimension_overrides]
	#Allows you to override the displayed values for dimensions
	enabled = true

	#The Dimensions to override
	[[dimension_overrides.dimensions]]
		name = "overworld"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is in The Overworld"
			state = ""
			largeImageKey = ["overworld"]
			largeImageText = "In the Overworld"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_nether"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is in The Nether"
			state = ""
			largeImageKey = ["nether"]
			largeImageText = "In the Nether"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "the_end"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is in The End"
			state = ""
			largeImageKey = ["end"]
			largeImageText = "In the End"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "overworldmirror:overworld"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is in the Overworld Mirror"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/mirror.png"]
			largeImageText = "Exploring The Amplified Overworld Mirror"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "ad_astra:glacio"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is on Glacio"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/glacio.png"]
			largeImageText = "Exploring Glacio"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "ad_astra:mars"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is on Mars"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/mars.png"]
			largeImageText = "Exploring Mars"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "ad_astra:moon"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is on Luna"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/moon.png"]
			largeImageText = "Exploring Luna"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "ad_astra:mercury"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is on Mercury"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/mercury.png"]
			largeImageText = "Exploring Mercury"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "ad_astra:venus"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is on Venus"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/venus.png"]
			largeImageText = "Exploring Venus"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "ad_astra:glacio_orbit"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is in orbit over Glacio"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/orbit.png"]
			largeImageText = "In Space"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "ad_astra:mars_orbit"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is in orbit over Mars"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/orbit.png"]
			largeImageText = "In Space"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "ad_astra:moon_orbit"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is in orbit over Luna"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/orbit.png"]
			largeImageText = "In Space"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "ad_astra:mercury_orbit"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is in orbit over Mercury"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/orbit.png"]
			largeImageText = "In Space"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "ad_astra:venus_orbit"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is in orbit over Venus"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/orbit.png"]
			largeImageText = "In Space"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "ad_astra:earth_orbit"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is in orbit over Earth"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/orbit.png"]
			largeImageText = "In Space"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "deeperdarker:otherside"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is in the Deep Dark"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/deepdark.png"]
			largeImageText = "Exploring The Otherside"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "undergarden:undergarden"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is in the Undergarden"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/undergarden.png"]
			largeImageText = "Exploring the Undergarden"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "sgjourney:abydos"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is on Abydos"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/abydos.png"]
			largeImageText = "Exploring Abydos"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "sgjourney:athos"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is on Athos"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/athos.png"]
			largeImageText = "Exploring Athos"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "sgjourney:cavum_tenebrae"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is on Cavum Tenebrae"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/cavum_tenebrae.png"]
			largeImageText = "Exploring a Black Hole"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "sgjourney:chulak"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is on Chulak"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/chulak.png"]
			largeImageText = "Exploring Chulak"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "sgjourney:rima"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is on Rima"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/rima.png"]
			largeImageText = "Exploring Rima"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "sgjourney:lantea"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is in Atlantis"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/lantea.png"]
			largeImageText = "Exploring Lantea"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

	[[dimension_overrides.dimensions]]
		name = "sgjourney:unitas"

		[[dimension_overrides.dimensions.presence]]
			type = "PLAYING"
			description = "{{player.name}} is on Unitas"
			state = ""
			largeImageKey = ["https://raw.githubusercontent.com/RedAngel121/Stargate-ReLeveled/refs/heads/main/config/simple-rpc/assets/unitas.png"]
			largeImageText = "Exploring Unitas"
			smallImageKey = ["mclogo"]
			smallImageText = "{{game.mods}} mods installed"
			streamingActivityUrl = "https://twitch.tv/twitch"
			buttons = []

